apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: htcondor-worker-arm64
  name: htcondor-worker-arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app: htcondor-worker-arm64
  template:
    metadata:
      labels:
        app: htcondor-worker-arm64
    spec:
      containers:
      - name: htcondor-worker-arm64
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "/preStop.sh"]
        imagePullPolicy: Always
        image: marcog94/worker:9.x-arm64
        # resources:
        #   requests:
        #     memory: "1.0Gi"
        #     cpu: "500m"
        #   limits:
        #     memory: "1.0Gi"
        #     cpu: "500m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-central-manager"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
          - name: pool-password
            mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
