apiVersion: v1
kind: PersistentVolume
metadata:
  name: htcondor-worker-slib-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/marco/shared-lib
    type: DirectoryOrCreate