apiVersion: v1
kind: Service
metadata:
  labels:
    app: htcondor-schedd
  name: htcondor-schedd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: htcondor-schedd
  type: ClusterIP
