apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: htcondor-schedd
  name: htcondor-schedd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htcondor-schedd
  template:
    metadata:
      labels:
        app: htcondor-schedd
    spec:
      containers:
      - name: htcondor-schedd
        imagePullPolicy: Always
        image: marcog94/scheduler:9.x
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "1000m"
          limits:
            memory: "1.0Gi"
            cpu: "1000m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-central-manager"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
          - name: wf-volume
            mountPath: /home/marco/wf
          - name: pool-password
            mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/htcondor-schedd-liveness
          initialDelaySeconds: 10
          periodSeconds: 30
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: atm-test-new
      volumes:
      - name: wf-volume
        persistentVolumeClaim:
          claimName: htcondor-schedd-pvc
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
