apiVersion: v1
kind: PersistentVolume
metadata:
  name: htcondor-schedd-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/marco
    type: Directory