kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim
spec:
  volumeName: nfs-pv
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi