apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.5.39
    path: /nfs
    readonly: no