kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pods-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "create", "get", "list"]
[root@vm72 ~]# cat serviceaccount-creator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator
